# Generated by Django 6.0.1 on 2026-01-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Catégorie d'âge",
                'verbose_name_plural': "Catégories d'âge",
                'db_table': 'category_age',
                'ordering': ['age_min'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoryGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie de genre',
                'verbose_name_plural': 'Catégories de genre',
                'db_table': 'category_genre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Saison',
                'verbose_name_plural': 'Saisons',
                'db_table': 'saison',
                'ordering': ['-periode'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChampionnatCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('date_champ', models.DateField(verbose_name='Date du championnat')),
                ('lieu_deroulement', models.CharField(max_length=150, verbose_name='Lieu')),
                ('category_age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.categoryage', verbose_name="Catégorie d'âge")),
                ('category_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.categorygenre', verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Championnat/Compétition',
                'verbose_name_plural': 'Championnats/Compétitions',
                'db_table': 'championnat_competition',
                'ordering': ['-date_champ'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EquipeAdverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('category_age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.categoryage', verbose_name="Catégorie d'âge")),
                ('category_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.categorygenre', verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Équipe adverse',
                'verbose_name_plural': 'Équipes adverses',
                'db_table': 'equipe_adverse',
                'ordering': ['nom'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.categorygenre', verbose_name='Genre')),
                ('category_age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.categoryage', verbose_name="Catégorie d'âge")),
            ],
            options={
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
                'db_table': 'joueur',
                'ordering': ['nom', 'prenom'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rencontre', models.DateTimeField(verbose_name='Date de la rencontre')),
                ('lieu_rencontre', models.CharField(max_length=150, verbose_name='Lieu')),
                ('championnat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.championnatcompetition', verbose_name='Championnat')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'db_table': 'match_day',
                'ordering': ['-date_rencontre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MatchDayEquipeAdverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe_adverse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.equipeadverse')),
                ('match_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.matchday')),
            ],
            options={
                'verbose_name': 'Match - Équipe adverse',
                'verbose_name_plural': 'Matchs - Équipes adverses',
                'db_table': 'match_day_equipe_adverse',
                'managed': True,
                'unique_together': {('match_day', 'equipe_adverse')},
            },
        ),
        migrations.AddField(
            model_name='matchday',
            name='equipes_adverses',
            field=models.ManyToManyField(through='club.MatchDayEquipeAdverse', to='club.equipeadverse', verbose_name='Équipes adverses'),
        ),
        migrations.CreateModel(
            name='PalmaresClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('competition', models.CharField(max_length=200)),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.categorygenre', verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Palmarès',
                'verbose_name_plural': 'Palmarès',
                'db_table': 'palmares_club',
                'ordering': ['-annee'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='matchday',
            name='saison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.saison', verbose_name='Saison'),
        ),
    ]
