# Generated by Django 6.0.1 on 2026-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchday',
            name='set1_adverse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 1 - Adverse'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='set1_club',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 1 - Club'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='set2_adverse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 2 - Adverse'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='set2_club',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 2 - Club'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='set3_adverse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 3 - Adverse'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='set3_club',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 3 - Club'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='set4_adverse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 4 - Adverse'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='set4_club',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 4 - Club'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='set5_adverse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 5 - Adverse (Tie-break)'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='set5_club',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 5 - Club (Tie-break)'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='sets_adverse',
            field=models.IntegerField(blank=True, null=True, verbose_name="Sets gagnés par l'adversaire"),
        ),
        migrations.AddField(
            model_name='matchday',
            name='sets_club',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sets gagnés par notre club'),
        ),
    ]
