# Generated by Django 6.0.1 on 2026-01-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_matchday_set1_adverse_matchday_set1_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='joueur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
